# Generated by Django 4.2 on 2025-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choices",
            new_name="Choice",
        ),
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(upload_to="notes/"),
        ),
    ]
